name: supermarket-objects
channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.17.2 # so we get the mkl libs as well
  - pandas=1.1.5
  - pip:
    - pytest==4.6.3
    - pylint==2.3.1
    - flask==1.1.1
    - gunicorn==20.0.4
    - opencv-python==4.5.2.52
    - torch==1.8.1
    - torchvision===0.9.1
    - requests==2.25.1